// This file is autogenerated
VIZ.fileSizes = {
  "data/average-actual-delays.json": 8949,
  "data/delay.json": 2822327,
  "data/marey-header.json": 1594,
  "data/marey-trips.json": 818145,
  "data/spider.json": 2133,
  "data/station-network.json": 8830,
  "data/turnstile-gtfs-mapping.json": 1644,
  "data/turnstile-heatmap.json": 2542709
};