// This file is autogenerated
VIZ.fileSizes = {
  "data/delay.json": 4499925,
  "data/marey-header.json": 1594,
  "data/marey-trips.json": 818145,
  "data/spider.json": 2133,
  "data/station-network.json": 8830,
  "data/turnstile-heatmap.json": 2542709
};